/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/{type_of_client}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chat_ws"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatMessage: {
            message: string;
            message_font: string;
            username: string;
            username_color: components["schemas"]["RgbColor"];
        };
        /** @enum {string} */
        ClientType: "User" | "ChatFrontend";
        OkayMessage: {
            ok: components["schemas"]["ThisIsOk"];
        };
        RgbColor: number[];
        /** @enum {string} */
        ThisIsOk: "OK";
        UserFields: {
            message_font: string;
            username: string;
            username_color: components["schemas"]["RgbColor"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is alive!! */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat_ws: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Determines whether the client provides to the chat or recieves chat messages */
                type_of_client: components["schemas"]["ClientType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moving over from http to the websocket */
            101: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
