[package]
name = "double_ues_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
axum = { version = "0.8.9", features = ["ws", "macros"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
headers = "0.4"
tokio-tungstenite = "0.30.0"
tower-http = { version = "0.7.1", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151" }
uuid = {version = "1.26", features = ["v4"] }
dashmap = "6.2.1"

utoipa = {version = "6.0.0", features = ["axum_extras"]}
utoipa-scalar = {version = "0.4.0", features = ["axum"]}
